# Paramètres de connexion PostgreSQL - HellMetz Festival

# URL de connexion à la base de données localhost peut être
# remplacé par une adresse IP ou le nom du serveur
#db.url=jdbc:postgresql://192.168.1.200:5432/hellmetz_db
db.url=jdbc:postgresql://10.226.35.200:5432/hellmetz_db

# Nom d'utilisateur de la base de données
db.user=hellmetz

# Mot de passe de la base de données
db.password=MotDePasseBTS!

# Pilote ou driver utilisé pour se connecter à la base de données
# Peut être modifier en fonction du moteur de base de données utilisé
db.driver=org.postgresql.Driver
